/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Version_treeIndexRouteImport } from './routes/version_tree/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as GeneratorIndexRouteImport } from './routes/generator/index'
import { Route as Version_treeCompareIndexRouteImport } from './routes/version_tree/compare/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Version_treeIndexRoute = Version_treeIndexRouteImport.update({
  id: '/version_tree/',
  path: '/version_tree/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorIndexRoute = GeneratorIndexRouteImport.update({
  id: '/generator/',
  path: '/generator/',
  getParentRoute: () => rootRouteImport,
} as any)
const Version_treeCompareIndexRoute =
  Version_treeCompareIndexRouteImport.update({
    id: '/version_tree/compare/',
    path: '/version_tree/compare/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/generator/': typeof GeneratorIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/version_tree/': typeof Version_treeIndexRoute
  '/version_tree/compare/': typeof Version_treeCompareIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/generator': typeof GeneratorIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/version_tree': typeof Version_treeIndexRoute
  '/version_tree/compare': typeof Version_treeCompareIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/generator/': typeof GeneratorIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/version_tree/': typeof Version_treeIndexRoute
  '/version_tree/compare/': typeof Version_treeCompareIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/generator/'
    | '/settings/'
    | '/version_tree/'
    | '/version_tree/compare/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/generator'
    | '/settings'
    | '/version_tree'
    | '/version_tree/compare'
  id:
    | '__root__'
    | '/'
    | '/generator/'
    | '/settings/'
    | '/version_tree/'
    | '/version_tree/compare/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeneratorIndexRoute: typeof GeneratorIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  Version_treeIndexRoute: typeof Version_treeIndexRoute
  Version_treeCompareIndexRoute: typeof Version_treeCompareIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version_tree/': {
      id: '/version_tree/'
      path: '/version_tree'
      fullPath: '/version_tree/'
      preLoaderRoute: typeof Version_treeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator/': {
      id: '/generator/'
      path: '/generator'
      fullPath: '/generator/'
      preLoaderRoute: typeof GeneratorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/version_tree/compare/': {
      id: '/version_tree/compare/'
      path: '/version_tree/compare'
      fullPath: '/version_tree/compare/'
      preLoaderRoute: typeof Version_treeCompareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeneratorIndexRoute: GeneratorIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  Version_treeIndexRoute: Version_treeIndexRoute,
  Version_treeCompareIndexRoute: Version_treeCompareIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
